FORMAT: 1A
HOST: https://contactdata.herokuapp.com/

# ContactData

A simple API allowing users to interact with contact info.

### Allowed HTTPs requests:
<pre>
POST    : To create resource 
PUT     : Update resource
GET     : Get a resource or list of resources
DELETE  : To delete resource
</pre>

### Description Of Usual Server Responses:
- 200 `OK` - the request was successful (some API calls may return 201 instead).
- 201 `Created` - the request was successful and a resource was created.
- 204 `No Content` - the request was successful but there is no representation to return (i.e. the response is empty).
- 400 `Bad Request` - the request could not be understood or was missing required parameters.
- 404 `Not Found` - resource was not found.
- 405 `Method Not Allowed` - requested method is not supported for resource.

---
**User attributes:**

- id `(Number)` : unique identifier. 
- name `(String)` : Name of a person.
- phone `(String)` : Phone Number. 
- email `(String)` : email adrress.
---

## Informations : [/contacts/]
---

### Get all students[GET]

+ Response 200 (application/json)
[{"_id":"5cbeb852109802230017b7b3","name":"farhan","phone":"01521444","email":"fsss@gmalil"},{"_id":"5cbeb891109802230017b7b4","name":"Naidim","phone":"012421444","email":"nmm@gmalil"},{"_id":"5cbed5d5be500f0004d6cabc","name":"Raju","phone":"01388421444","email":"si.summ@gmalil"},{"_id":"5cbed5ffbe500f0004d6cabd","name":"Niaz","phone":"01488421444","email":"neumm@gmalil"}]
### Add new student [POST]

+ Request (application/json)

        {
            "name": "Shuvo",
            "phone": "01789101112",
            "email": "fxyzzz@gmail.com"
        }


+ Response 201 (application/json)

    + Headers

            Location: /contacts/id

    + Body

            {   
                "_id": "5cbc5ea01c9d440000e782fb",
                "name": "Shuvo",
                "phone": "01789101112",
                "email": "fxyzzz@gmail.com"
            }
            
## Access Informations by id : [/contacts/{id}]

---

### Get a spacific data [GET]


+ Parameters
    + id (number) - ID of the User in the form of a string

+ Response 200 (application/json)
    
        {
            "_id": "5cbc5ea01c9d440000e782fb",
            "name": "Shuvo",
            "phone": "01789101112",
            "email": "fxyzzz@gmail.com"   
        }
 

### Delete  a spacific data [DELETE]


+ Parameters
    + id (number) - ID of the User in the form of a string

+ Response 200